//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtusaProject_HandmadeproductSelling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.O_Invoice = new HashSet<O_Invoice>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int P_ID { get; set; }
        [Required(ErrorMessage = "Please Enter Product name")]
        public string P_name { get; set; }
        [Required(ErrorMessage = "Input Image")]
        public string P_image { get; set; }
        [Required(ErrorMessage = "Please enter description ")]
        public string P_desc { get; set; }
        [Required(ErrorMessage = "Enter price details")]
        [Range(0, 50000, ErrorMessage = "Price not more than 50000")]
        public Nullable<int> P_price { get; set; }
        [Required(ErrorMessage = "Enter available stock")]
        public Nullable<int> P_quantity { get; set; }
        public Nullable<int> add_pid { get; set; }
        public Nullable<int> addadmin_pid { get; set; }
        public Nullable<int> adduser_pid { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Category Category { get; set; }
        public virtual Registration Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_Invoice> O_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
