//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtusaProject_HandmadeproductSelling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public int P_ID { get; set; }
        [Required(ErrorMessage = "Product name")]
        public string P_name { get; set; }
        [Required(ErrorMessage = "Image required")]
        public string P_image { get; set; }
        [Required(ErrorMessage = "Enter describtion")]
        public string P_desc { get; set; }
        [Required(ErrorMessage = "Prize detail is important")]
        public Nullable<int> P_price { get; set; }
        [Required(ErrorMessage = "Enter available stock")]
        public Nullable<int> P_quantity { get; set; }
        public Nullable<int> add_pid { get; set; }
        public Nullable<int> addadmin_pid { get; set; }
        public Nullable<int> adduser_pid { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Category Category { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
