//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtusaProject_HandmadeproductSelling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int custID { get; set; }
        [Required(ErrorMessage = "First Name")]
        public string f_name { get; set; }
        [Required(ErrorMessage = "Last Name")]
        public string l_name { get; set; }
        [Required(ErrorMessage = "Enter Email ")]
        public string email { get; set; }
        [Required(ErrorMessage = "Required")]
        public string gender { get; set; }
        [RegularExpression(@"[6-9]\d{9}", ErrorMessage = "Invalid Mobile No")]
        public Nullable<long> phone { get; set; }
        [Required(ErrorMessage = "Enter Password")]
        [RegularExpression("[0-9a-zA-Z]{6,12}", ErrorMessage = "Invalid Password format")]
        public string c_password { get; set; }
        [Compare("c_password", ErrorMessage = "Password Mismatch")]
        public string Con_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
